### ISSUE TITLE
How to set up the environment?

### ISSUE THREAD

**Issue by anshul119** [alexmk92/CUDACam#1]
Hello Alex!

I been working some project on similar lines. I am facing a small issue here, could you please help me out with this?

I am using cuda 7, openCV 2.4.9 and Visual Studio 13.

I can run cuda codes on VS separately. I can run openCV programs on VS alone but when I try to do both opencv and cuda in same project i get errors. I am not able to set up the environment for opencv + cuda. Could you please help me with this?

thanks!

**Comment by alexmk92** [comment]
Hi Anshul.  Could you confirm that you have linked your binaries correctly and that you have the 32 bit binaries.   I had problems compiling on 64bit

**Comment by anshul119** [comment]
Thank you for your reply Alex!

I have 64x system so I am using 64x cuda and opencv version.

I am giving path to all the dlls and include folders correctly even then its not working  in VS13. 

-----Original Message-----

**Comment by alexmk92** [comment]
I also have a x64 machine and had a similar linker problem. When I switched to x86 binaries it worked.   Did you download and look at my solution?  It's been a while since I looked at it, maybe viewing my project configuration will help.

**Comment by anshul119** [comment]
With my present configurations it didn't work.

I will try 86x. So I need to use both cuda and opencv 86x right?

-----Original Message-----

**Comment by alexmk92** [comment]
Yes, thats correct - it's not guaranteed to fix it but I remember the 64 bit libs causing me issues.

**Comment by anshul119** [comment]
hi

I tried with 86x binaries, still doesn't work. and when i open this proect, it gies me an error. it first ask me to choose an app to open CUDA_assign.vcxprorj and gives me no options to select from.

**Comment by anshul119** [comment]
I resolved the problem by switching to Ubuntu. I used GCC + Cmake. If anyone else is experiencing the same problem I have a readme file for the same, don't hesitate to shoot me a mail.
